### ISSUE TITLE
Duda De rubrica

### ISSUE THREAD

**Issue by efrenlo** [jceballosm/infraweb#1]
Profe tenemos dudas sobre la rubrica del cartel, en los apartados nos piden que pongamos objetivo general, objetivos específicos y resultados esperados. no encontramos la manera de como se puedan incluir en el cartel. Las 2 rubricas son muy similares.

**Comment by jceballosm** [comment]
Pueden ponerlos ya sea en una figura o dentro de alguna forma (rectángulo
por ejemplo)

**Comment by efrenlo** [comment]
Molestando la duda es si el objetivo general y específicos son de git como tal o del cartel

**Comment by jceballosm** [comment]
Del tema, y el tema es GIT
